FROM docker.elastic.co/kibana/kibana-oss:7.10.0
RUN bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-anomaly-detection/opendistroAnomalyDetectionKibana-1.12.0.0.zip
#COPY kibana-docker start-kibana
#CMD tail -f /dev/null
